import type { Metadata } from "next";
import { Outfit, Syne } from "next/font/google";
import "./globals.css";

const font = Outfit({
  variable: "--font-taste",
  subsets: ["latin"],
});

const headingFont = Syne({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${font.variable} ${headingFont.variable} h-full antialiased font-sans`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
